/**
 * Generated by audio-clipper — do not hand-edit.
 * Re-make with:  curl -X POST localhost:4611/api/medley
 * then copy out/medley.mp3 + out/medley.ts into the site.
 */
export type Chapter = { num: string; title: string; start: number; end: number };

/** One continuous piece, 10 chapters, 1.2s of silence between them. */
export const MEDLEY_DURATION = 436.147;
export const MEDLEY_CHAPTERS: Chapter[] = [
  { num: '01', title: "Sea Rising", start: 0, end: 29.877 },
  { num: '02', title: "In Memory of Those Who Chose the Sea", start: 31.077, end: 80.527 },
  { num: '03', title: "A Dream So Real", start: 81.727, end: 136.628 },
  { num: '04', title: "Wait, Why Is the Dream So Real?", start: 137.828, end: 171.063 },
  { num: '05', title: "Wake Up", start: 172.263, end: 221.669 },
  { num: '06', title: "The Heart of the Jellyfish", start: 222.869, end: 289.103 },
  { num: '07', title: "You Shall See", start: 290.303, end: 312.748 },
  { num: '08', title: "What Belongs to the Sea Will Always Return to the Sea", start: 313.948, end: 351.808 },
  { num: '09', title: "The Day After — Without Us", start: 353.008, end: 388.07 },
  { num: '10', title: "Sea Risen", start: 389.27, end: 436.147 },
];
